### DISCUSSION TITLE
Server can not be reached

### DISCUSSION THREAD

**Discussion by Kampi** [TomBursch/kitchenowl#780] [Q&A]
Hi,

I want to run KitchenOwl on my NAS by using Docker. So I´ve used the default Docker-Compose file from the project repository and run the container. I leave the default password and name for now because I want to test the setup. I will change them later so please don´t wonder.

```
version: "3"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: kitchenowl
      POSTGRES_USER: kitchenowl
      POSTGRES_PASSWORD: example
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  back:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    ports:
      - "8173:8080"
    networks:
      - default
    environment:
      JWT_SECRET_KEY: PLEASE_CHANGE_ME
      DB_DRIVER: postgresql
      DB_HOST: db
      DB_NAME: kitchenowl
      DB_USER: kitchenowl
      DB_PASSWORD: example
    depends_on:
      - db
    volumes:
      - ./data:/data

volumes:
  kitchenowl_files:
    driver: local
  kitchenowl_db:
    driver: local

networks:
  default:
```

But when I try to connect with the latest Windows app by using the address https://192.168.178.103:8173 the app is always saying that the server can not be reached.

Neither the db nor the backend are reporting anything suspicious. Please see the attached logs

[kitchenowl-back-1.html.txt](https://github.com/user-attachments/files/20736112/kitchenowl-back-1.html.txt)
[kitchenowl-db-1.html.txt](https://github.com/user-attachments/files/20736113/kitchenowl-db-1.html.txt)
