### ISSUE TITLE
Bug: No longer able to add categories 

### ISSUE THREAD

**Issue by Grijnak** [TomBursch/kitchenowl#132]
### Is this urgent?

None

### What parts are affected

Frontend

### What are the Server/Client versions of KitchenOwl

0.3.12

### What's the problem 🤔

After upgrading kitchenowl it is no longer possible to add a new category. Adding tags, shopping list etc. works. I know this was working in 0.3.10

I should note that I did some work on the nginx acting as a reverse proxy to the dockerized instance of kitchenowl, though it would surprise me if that were the cause of this bug, since the request never reaches the backend.

To reproduce this bug go to Profile -> Server -> Click on the + next to "Categories" -> enter a name -> click "Add". Nothing changes, whereas I expected a new category to appear in the list. 

No activity is logged in the backend, output from the javascript console is attached.

### Share your logs

```log
Uncaught Error:         BlocProvider.of() called with a context that does not contain a minified:of.
    d https://<URL censored>/main.dart.js:5007
    bS https://<URL censored>/main.dart.js:29802
    0 https://<URL censored>/main.dart.js:123940
    s https://<URL censored>/main.dart.js:6282
    $2 https://<URL censored>/main.dart.js:51655
    $1 https://<URL censored>/main.dart.js:51649
    aM2 https://<URL censored>/main.dart.js:52634
    Ty https://<URL censored>/main.dart.js:52636
    $0 https://<URL censored>/main.dart.js:52055
    Eb https://<URL censored>/main.dart.js:6410
    rE https://<URL censored>/main.dart.js:51979
    $0 https://<URL censored>/main.dart.js:52023
    bGh https://<URL censored>/main.dart.js:6442
    bGF https://<URL censored>/main.dart.js:6444
    $1 https://<URL censored>/main.dart.js:51599
    bIE https://<URL censored>/main.dart.js:5088
    s https://<URL censored>/main.dart.js:5096
    bD1 https://<URL censored>/main.dart.js:6251
    <anonymous> https://<URL censored>/main.dart.js:140419
    c https://<URL censored>/main.dart.js:32
    bpD https://<URL censored>/main.dart.js:6449
    n9 https://<URL censored>/main.dart.js:6538
    X_ https://<URL censored>/main.dart.js:51986
    jU https://<URL censored>/main.dart.js:51984
    ep https://<URL censored>/main.dart.js:51901
    j6 https://<URL censored>/main.dart.js:51902
    $1 https://<URL censored>/main.dart.js:38703
    bAT https://<URL censored>/main.dart.js:4963
    byv https://<URL censored>/main.dart.js:7377
    bEP https://<URL censored>/main.dart.js:36887
    s https://<URL censored>/main.dart.js:36883
    a5 https://<URL censored>/main.dart.js:8736
    dA https://<URL censored>/main.dart.js:424
    bFj https://<URL censored>/main.dart.js:201
    bbQ https://<URL censored>/main.dart.js:186
    s https://<URL censored>/main.dart.js:6282
    $2 https://<URL censored>/main.dart.js:51655
    r https://<URL censored>/main.dart.js:6268
    bbQ https://<URL censored>/main.dart.js:193
    Cm https://<URL censored>/main.dart.js:40087
    s https://<URL censored>/main.dart.js:6282
    $2 https://<URL censored>/main.dart.js:51655
    r https://<URL censored>/main.dart.js:6268
    Cm https://<URL censored>/main.dart.js:40092
    0 https://<URL censored>/main.dart.js:45128
    s https://<URL censored>/main.dart.js:6282
    $2 https://<URL censored>/main.dart.js:51655
    r https://<URL censored>/main.dart.js:6268
    $0 https://<URL censored>/main.dart.js:45132
    bcd https://<URL censored>/main.dart.js:1492
    s https://<URL censored>/main.dart.js:6282
    $2 https://<URL censored>/main.dart.js:51655
    r https://<URL censored>/main.dart.js:6268
    bIz https://<URL censored>/main.dart.js:1496
    bcd https://<URL censored>/main.dart.js:1477
    1 https://<URL censored>/main.dart.js:56759
    s https://<URL censored>/main.dart.js:6282
    $2 https://<URL censored>/main.dart.js:51655
    r https://<URL censored>/main.dart.js:6268
    aai https://<URL censored>/main.dart.js:56761
    $1 https://<URL censored>/main.dart.js:56751
    $0 https://<URL censored>/main.dart.js:56752
    xw https://<URL censored>/main.dart.js:37899
    s https://<URL censored>/main.dart.js:6282
    $2 https://<URL censored>/main.dart.js:51655
    r https://<URL censored>/main.dart.js:6268
    xw https://<URL censored>/main.dart.js:37903
    bd3 https://<URL censored>/main.dart.js:8849
    s https://<URL censored>/main.dart.js:6282
    $2 https://<URL censored>/main.dart.js:51655
    r https://<URL censored>/main.dart.js:6268
    bd3 https://<URL censored>/main.dart.js:8857
    bco https://<URL censored>/main.dart.js:36867
    s https://<URL censored>/main.dart.js:6282
    $2 https://<URL censored>/main.dart.js:51655
    r https://<URL censored>/main.dart.js:6268
    bco https://<URL censored>/main.dart.js:36869
    <anonymous> https://<URL censored>/main.dart.js:140908
    <anonymous> https://<URL censored>/main.dart.js:140902
    dartProgram https://<URL censored>/main.dart.js:140905
    <anonymous> https://<URL censored>/main.dart.js:140908
main.dart.js:5007:3
```

### Share your configuration

```yml
version: "3"
services:
  front:
    image: tombursch/kitchenowl-web:latest
    # environment:
    #   - BACK_URL=back:5000 # Optional should not be changed unless you know what youre doing
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - back
    networks:
      - default
  back:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    # ports: # Optional
    #   - "80:80" # http protocol
    #   - "5000:5000" # uwsgi protocol
    networks:
      - default
    environment:
      - JWT_SECRET_KEY=***
      # - FRONT_URL=http://localhost # Optional should not be changed unless you know what youre doing
    volumes:
      - kitchenowl_data:/data

volumes:
  kitchenowl_data:

networks:
  default:
```
