### ISSUE TITLE
Bug: No arm7 build on docker site for backend

### ISSUE THREAD

**Issue by schwanbeck** [TomBursch/kitchenowl#143]
### Is this urgent?

No

### What parts are affected

Backend

### What are the Server/Client versions of KitchenOwl

v0.3.13 

### What's the problem 🤔

Installing via `docker compose up` with suggested docker-compose.yml file gives error 
`[+] Running 0/1`
` ⠴ back Pulling`
`no matching manifest for linux/arm/v7 in the manifest list entries`

Checked under [docker site](https://hub.docker.com/layers/tombursch/kitchenowl/latest/images/sha256-035ed3789f2afb47f22bfbce394f2f96b5ca72943eb79eb0ea2a2792087d86d7?context=explore) and found no compilation for arm7 structure, though kitchenowl-web has one.

### Share your configuration

```yml
docker-compose.yml:

version: "3"
services:
  front:
    image:  tombursch/kitchenowl-web:latest
    # environment:
    #   - BACK_URL=back:5000 # Optional should not be changed unless you know what youre doing
    ports:
      - "8042:80"
    depends_on:
      - back
    networks:
      - default
  back:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    # ports: # Optional
    #   - "80:80" # http protocol
    #   - "5000:5000" # uwsgi protocol
    networks:
      - default
    environment:
      - JWT_SECRET_KEY=CHANGEME
      # - FRONT_URL=http://localhost # Optional should not be changed unless you know what youre doing
    volumes:
      - kitchenowl_data:/data

volumes:
  kitchenowl_data:

networks:
  default:
```
