### ISSUE TITLE
Bug: web frontend working in browser but not in app

### ISSUE THREAD

**Issue by Baton4986** [TomBursch/kitchenowl#187]
### Is this urgent?

None

### What parts are affected

Both

### What are the Server/Client versions of KitchenOwl

Docker Image Version: v68 / Android App Version: 0.4.5

### What's the problem 🤔

I can connect to the frontend via browser, but not via app (message: "Hmmmm. server can't be reached").

### Share your logs

```log
docker_front_1:
2023/06/28 16:45:10 [notice] 1#1: start worker process 36
127.0.0.1 - - [28/Jun/2023:16:45:40 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/7.88.1" "-"
127.0.0.1 - - [28/Jun/2023:16:46:10 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/7.88.1" "-"
127.0.0.1 - - [28/Jun/2023:16:46:40 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/7.88.1" "-"
127.0.0.1 - - [28/Jun/2023:16:47:10 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/7.88.1" "-"
127.0.0.1 - - [28/Jun/2023:16:47:40 +0000] "GET / HTTP/1.1" 200 1548 "-" "curl/7.88.1" "-"
```

### Share your configuration

```yml
Apache Reverse Proxy Settings:
        ServerName my.kitchenowl.domain
        ProxyPass / http://127.0.0.1:8001/ retry=0
        ProxyPassReverse / http://127.0.0.1:8001/


docker-compose.yml:
version: "3"
services:
    front:
        image: tombursch/kitchenowl-web:latest
        ports:
        - "8001:80"
        depends_on:
        - back
        networks:
        - default
    back:
        image: tombursch/kitchenowl:latest
        restart: unless-stopped
        networks:
        - default
        environment:
        - JWT_SECRET_KEY=mysecretkey
        volumes:
        - kitchenowl_data:/data

volumes:
    kitchenowl_data:

networks:
    default:
```
