### ISSUE TITLE
Bug: SSL error when attempting to import from recipes.instantpot.com

### ISSUE THREAD

**Issue by SeeJayEmm** [TomBursch/kitchenowl#198]
### Is this urgent?

No

### What parts are affected

Backend

### What are the Server/Client versions of KitchenOwl

v0.4.6(77) | Server v72

### What's the problem 🤔

Trying to import the recipe on https://recipes.instantpot.com/recipe/chicken-tikka-masala/ returns "An error occurred".  Checking on the logs I found the snippet included below which indicates an SSL problem. The site https://recipes.instantpot.com has a valid SSL certificate, as near as I can tell.

### Share your logs

```log
[2023-07-16 20:49:23,437] ERROR in config: HTTPSConnectionPool(host='recipes.instantpot.com', port=443): Max retries exceeded with url: /recipe/chicken-tikka-masala/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))
ERROR:app.config:HTTPSConnectionPool(host='recipes.instantpot.com', port=443): Max retries exceeded with url: /recipe/chicken-tikka-masala/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))
```

### Share your configuration

```yml
version: "3"
services:
  front:
    image: tombursch/kitchenowl-web:latest
    # environment:
    #   - BACK_URL=back:5000 # Optional should not be changed unless you know what youre doing
    # Commenting out port bindings
    #ports:
    #  - "2080:80"
    depends_on:
      - back
    networks:
      - net
  back:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    # ports: # Optional
    #   - "80:80" # http protocol
    #   - "5000:5000" # uwsgi protocol
    networks:
      - net
    environment:
      - JWT_SECRET_KEY="obfuscated"
      # - FRONT_URL=http://localhost # Optional should not be changed unless you know what youre doing
    volumes:
      - kitchenowl_data:/data

volumes:
  kitchenowl_data:

networks:
  net:
    external: true
```
