### ISSUE TITLE
Bug:  Process ` kitchenowl uWSGI http 1`  uses an a LOT of memory (> 4 GB)

### ISSUE THREAD

**Issue by burghoffdavid** [TomBursch/kitchenowl#199]
### Is this urgent?

Yes

### What parts are affected

Backend

### What are the Server/Client versions of KitchenOwl

latest, fresh pull from today, should be v73 then? 

### What's the problem 🤔

The process ` kitchenowl uWSGI http 1`  hogs a LOT of RAM and never lets go of it, even after letting it run for a couple of hours. Might be some memory leak.  Also nuked the whole thing a couple of times to rule out weird corrupt db issues, didnt help...

Also tried to manually edit the uswgi.ini file and add some limiters, but sadly this did not help either: 

````ini
[uwsgi]
...
enable-threads  = true
threads = 100
harakiri = 30
max-request = 50
...
````

Read some reports that this is quite common with uWSGI. If you need more logs / info let me know  :v: 
Love the whole app / setup overall :grinning: 

### Share your logs

```log
Backend Logs:
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/01-kitchenowl-customization.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/07/17 21:02:47 [notice] 1#1: using the "epoll" event method
2023/07/17 21:02:47 [notice] 1#1: nginx/1.24.0
2023/07/17 21:02:47 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2023/07/17 21:02:47 [notice] 1#1: OS: Linux 6.3.8-100.fc37.x86_64
2023/07/17 21:02:47 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1073741816:1073741816
2023/07/17 21:02:47 [notice] 1#1: start worker processes
2023/07/17 21:02:47 [notice] 1#1: start worker process 37
2023/07/17 21:02:47 [notice] 1#1: start worker process 38
2023/07/17 21:02:47 [notice] 1#1: start worker process 39
2023/07/17 21:02:47 [notice] 1#1: start worker process 40
127.0.0.1 - - [17/Jul/2023:21:03:17 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:03:47 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:04:17 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:04:48 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:05:18 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:05:48 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:06:18 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:06:48 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"


Frontend Logs:
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/01-kitchenowl-customization.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/07/17 21:02:47 [notice] 1#1: using the "epoll" event method
2023/07/17 21:02:47 [notice] 1#1: nginx/1.24.0
2023/07/17 21:02:47 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2023/07/17 21:02:47 [notice] 1#1: OS: Linux 6.3.8-100.fc37.x86_64
2023/07/17 21:02:47 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1073741816:1073741816
2023/07/17 21:02:47 [notice] 1#1: start worker processes
2023/07/17 21:02:47 [notice] 1#1: start worker process 37
2023/07/17 21:02:47 [notice] 1#1: start worker process 38
2023/07/17 21:02:47 [notice] 1#1: start worker process 39
2023/07/17 21:02:47 [notice] 1#1: start worker process 40
127.0.0.1 - - [17/Jul/2023:21:03:17 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:03:47 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:04:17 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:04:48 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:05:18 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:05:48 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:06:18 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:06:48 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:07:19 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:07:49 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:08:19 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:08:49 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:09:19 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:09:50 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:10:20 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:10:50 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:11:20 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:11:50 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:12:21 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:12:51 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:13:21 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:13:51 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:14:21 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:14:52 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:15:22 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:15:52 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:16:22 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
127.0.0.1 - - [17/Jul/2023:21:16:52 +0000] "GET / HTTP/1.1" 200 1547 "-" "curl/8.1.2" "-"
```

### Share your configuration

```yml
version: "3"
services:
  front:
    image: tombursch/kitchenowl-web:latest
    ports:
      - 6254:80
    depends_on:
      - back
    networks:
      - default
  back:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    ports: # Optional
      - 6253:80 # http protocol
    networks:
      - default
    environment:
      - JWT_SECRET_KEY=REDACTED
    volumes:
      - kitchenowl_data:/data

volumes:
  kitchenowl_data:

networks:
  default:
```

**Comment by TomBursch** [comment]
Honestly, I have no idea what the issue could be 😄 
What happens if you limit the memory of the system using [`--memory=400m`](https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory)?

For anyone else looking at this issue, you can view how much memory a container is using with `docker stats CONTAINER_NAME` and the backend should use something in between 60-300mb.

**Comment by TomBursch** [comment]
Just to clarify, are you the same person that I talked to on the matrix channel?

**Comment by burghoffdavid** [comment]
Nope I am someone else 😅 Will try the suggested fix in ~30 min

**Comment by burghoffdavid** [comment]
But glad to hear I am not the only one^^

**Comment by TomBursch** [comment]
> Nope I am someone else
> But glad to hear I am not the only one^^

Well, I'm not 😂 I'll update all dependencies and push a new version, maybe that might already solve the issue

**Comment by burghoffdavid** [comment]
>What happens if you limit the memory of the system using [--memory=400m](https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory)?

Then it keeps respawning the ` uWSGI http 1 ` process as soon as it runs out of memory, logs:
[kitchenowl_back_1.log](https://github.com/TomBursch/kitchenowl/files/12097845/kitchenowl_back_1.log)

Nevertheless, CRUD operations all still seem to function without a noticeable delay, very weird :thinking:

**Comment by TomBursch** [comment]
Once the [CI](https://github.com/TomBursch/kitchenowl-backend/actions/runs/5601519845) completes (~20min), could you pull the latest image and try again? Although I doubt that this will change anything.

**Comment by meliache** [comment]
> Just to clarify, are you the same person that I talked to on the matrix channel?

I am the person who talked as _elimik_ in the matrix channel (have cryptographic proof for that [on keyoxide](https://keyoxide.org/546908C782383AD0E7D894EC1B8F95C8125DCE31)). I had seen the same issue, my logs (same as in the matrix channel) are here: https://0x0.st/HjTb.log. As I said I war running a simple http server with docker (version 24.0.2) under root. For completeness, my config is:

``` yaml
version: "3"
services:
  front:
    image: tombursch/kitchenowl-web:latest
    # environment:
    #   - BACK_URL=back:5000 # Optional should not be changed unless you know what youre doing
    ports:
      - "8866:80"
    depends_on:
      - back
    networks:
      - default
  back:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    networks:
      - default
    environment:
      - JWT_SECRET_KEY="REDACTED"
      # - FRONT_URL=http://localhost # Optional should not be changed unless you know what youre doing
    volumes:
      - kitchenowl_data:/data

volumes:
  kitchenowl_data:

networks:
  default:
```

My host system is Fedora 38 with Linux 6.3.12 running on a Hetzner VPS with an ARM CPU.

**Comment by burghoffdavid** [comment]
> Once the [CI](https://github.com/TomBursch/kitchenowl-backend/actions/runs/5601519845) completes (~20min), could you pull the latest image and try again? Although I doubt that this will change anything.

Pulled the new image and removed the RAM limitation, using ~ 5 GB RAM. [Logs
](https://github.com/TomBursch/kitchenowl/files/12098201/kitchenowl_back_1.log)


More info on my setup:
- x86 cpu (Old Macbook Pro)
- Host OS is also Fedora (37)
- Service is exposed via Cloudflare tunnels

**Comment by burghoffdavid** [comment]
As a workaround for now, the suggested setting [--memory=400m](https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory) or if you use docker-compose add the following to your docker-compose.yml:
````yml
...
  back:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    ports: # Optional
      - 80:80 # http protocol
    networks:
      - default
    environment:
      - JWT_SECRET_KEY=REDACTED
    volumes:
      - kitchenowl_data:/data
    deploy:
      resources:
        limits:
          memory: 400M
````


Seems to "fix" it for now.

**Comment by TomBursch** [comment]
I've made some bigger changes to the backend service. I would appreciate it if you some of you affected could report whether that has helped with this issue.

**Comment by burghoffdavid** [comment]
Just pulled the latest image, all kitchenowl processes now take up a stable ~300 MB RAM. Still quite a lot, but the main issue of eating up all the RAM until it crashes seems to be resolved :+1:

**Comment by meliache** [comment]
I just pulled and restardet the server and so far I only see the 300 MB RAM usage in the `docker stat` output

**Comment by TomBursch** [comment]
> Still quite a lot

Yeah, I'm aware, but I guess there is not much I can do about it unless I ditch python 😄 

Thanks everyone, will close this then.

**Comment by Tarow** [comment]
I am now facing the same issue (using the all-in-one docker image).
The `kitchenowl uWSGI http 1` process consumes 8GB of RAM.

Startup logs:
```
kitchenowl  | /opt/venv/lib/python3.12/site-packages/extruct/rdfa.py:88: SyntaxWarning: invalid escape sequence '\s'
kitchenowl  |   match = re.search(prefix + ": [^\s]+", head_element.get("prefix"))
kitchenowl  | /opt/venv/lib/python3.12/site-packages/pyRdfa/extras/httpheader.py:344: SyntaxWarning: invalid escape sequence '\-'
kitchenowl  |   """Parses a quoted string.
kitchenowl  | /opt/venv/lib/python3.12/site-packages/pyRdfa/extras/httpheader.py:355: SyntaxWarning: invalid escape sequence '\-'
kitchenowl  |   """Parses a token or a quoted-string.
kitchenowl  | /opt/venv/lib/python3.12/site-packages/pyRdfa/extras/httpheader.py:518: SyntaxWarning: invalid escape sequence '\-'
kitchenowl  |   """Parses a ()-style comment from a header value.
kitchenowl  | /opt/venv/lib/python3.12/site-packages/pyRdfa/termorcurie.py:61: SyntaxWarning: invalid escape sequence '\+'
kitchenowl  |   xml_application_media_type = re.compile("application/[a-zA-Z0-9]+\+xml")
kitchenowl  | /opt/venv/lib/python3.12/site-packages/pyRdfa/utils.py:131: SyntaxWarning: invalid escape sequence '\?'
kitchenowl  |   _unquotedChars = ':/\?=#~'
kitchenowl  | /usr/src/kitchenowl/migrations/env.py:21: DeprecationWarning: 'get_engine' is deprecated and will be removed in Flask-SQLAlchemy 3.2. Use 'engine' or 'engines[key]' instead. If you're using Flask-Migrate or Alembic, you'll need to update your 'env.py' file.
kitchenowl  |   return current_app.extensions['migrate'].db.get_engine()
kitchenowl  | /usr/src/kitchenowl/migrations/env.py:21: DeprecationWarning: 'get_engine' is deprecated and will be removed in Flask-SQLAlchemy 3.2. Use 'engine' or 'engines[key]' instead. If you're using Flask-Migrate or Alembic, you'll need to update your 'env.py' file.
kitchenowl  |   return current_app.extensions['migrate'].db.get_engine()
kitchenowl  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
kitchenowl  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Upgrading households: 0it [00:00, ?it/s]
kitchenowl  | [uWSGI] getting INI configuration from wsgi.ini
kitchenowl  | [uwsgi-static] added mapping for / => /var/www/web/kitchenowl
kitchenowl  | *** Starting uWSGI 2.0.25.1 (64bit) on [Mon Jul 15 09:35:31 2024] ***
kitchenowl  | compiled with version: 12.2.0 on 24 April 2024 13:24:45
kitchenowl  | os: Linux-6.9.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 21 Jun 2024 19:49:19 +0000
kitchenowl  | nodename: f0448cde01dd
kitchenowl  | machine: x86_64
kitchenowl  | clock source: unix
kitchenowl  | pcre jit disabled
kitchenowl  | detected number of CPU cores: 12
kitchenowl  | current working directory: /usr/src/kitchenowl
kitchenowl  | detected binary path: /opt/venv/bin/uwsgi
kitchenowl  | *** dumping internal routing table ***
kitchenowl  | [rule: 0] subject: path_info regexp: ^\/(?!api)[^\.]*$ action: static:/var/www/web/kitchenowl/index.html
kitchenowl  | *** end of the internal routing table ***
kitchenowl  | uWSGI running as root, you can use --uid/--gid/--chroot options
kitchenowl  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
kitchenowl  | your memory page size is 4096 bytes
kitchenowl  | detected max file descriptor number: 1073741816
kitchenowl  | !!! no /etc/mime.types file found !!!
kitchenowl  | - async cores set to 200 - fd table size: 1073741816
kitchenowl  | lock engine: pthread robust mutexes
kitchenowl  | thunder lock: disabled (you can enable it with --thunder-lock)
kitchenowl  | uWSGI http bound on [::]:8080 fd 3
kitchenowl  | uwsgi socket 0 bound to TCP6 address [::]:5000 fd 6
kitchenowl  | uWSGI running as root, you can use --uid/--gid/--chroot options
kitchenowl  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
kitchenowl  | Python version: 3.12.3 (main, Apr 10 2024, 03:39:08) [GCC 12.2.0]
kitchenowl  | Python main interpreter initialized at 0x75d4f6ca1668
kitchenowl  | uWSGI running as root, you can use --uid/--gid/--chroot options
kitchenowl  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
kitchenowl  | python threads support enabled
kitchenowl  | your server socket listen backlog is limited to 100 connections
kitchenowl  | your mercy for graceful operations on workers is 60 seconds
kitchenowl  | mapped 4307328 bytes (4206 KB) for 200 cores
kitchenowl  | *** Operational MODE: async ***
kitchenowl  | uWSGI running as root, you can use --uid/--gid/--chroot options
kitchenowl  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
kitchenowl  | spawned uWSGI master process (pid: 59)
kitchenowl  | spawned uWSGI worker 1 (pid: 60, cores: 200)
kitchenowl  | spawned uWSGI http 1 (pid: 61)
kitchenowl  | WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x75d4f6ca1668 pid: 60 (default app)
kitchenowl  | *** running gevent loop engine [addr:0x63e00f70dba0] ***
```

Running processes:
```
# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   2576  1408 ?        Ss   09:35   0:00 /bin/sh ./entrypoint.sh --ini wsgi.ini:web --gevent 200
root          59  0.0  0.1  62104 16000 ?        S    09:35   0:00 kitchenowl uWSGI master
root          60  3.7  1.5 1326528 249076 ?      Sl   09:35   0:05 kitchenowl uWSGI worker 1
root          61  1.2 52.4 8450712 8395308 ?     S    09:35   0:01 kitchenowl uWSGI http 1
root         270  0.3  0.0   2576  1536 pts/0    Ss   09:37   0:00 /bin/sh
root         276  0.0  0.0   8480  4352 pts/0    R+   09:37   0:00 ps aux
```

My compose file:
```yaml
services:
  kitchenowl:
    image: tombursch/kitchenowl:latest
    container_name: kitchenowl
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.kitchenowl.rule=Host(`kitchenowl.somedomain.com`)
      - traefik.http.routers.kitchenowl.entrypoints=websecure
      - traefik.http.routers.kitchenowl.middlewares=public-chain@file
      - traefik.http.services.kitchenowl.loadbalancer.server.port=8080
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
```

Setting the memory limit using docker compose causes the process to respawn all the time:
```
kitchenowl  | /opt/venv/lib/python3.12/site-packages/extruct/rdfa.py:88: SyntaxWarning: invalid escape sequence '\s'
kitchenowl  |   match = re.search(prefix + ": [^\s]+", head_element.get("prefix"))
kitchenowl  | /opt/venv/lib/python3.12/site-packages/pyRdfa/extras/httpheader.py:344: SyntaxWarning: invalid escape sequence '\-'
kitchenowl  |   """Parses a quoted string.
kitchenowl  | /opt/venv/lib/python3.12/site-packages/pyRdfa/extras/httpheader.py:355: SyntaxWarning: invalid escape sequence '\-'
kitchenowl  |   """Parses a token or a quoted-string.
kitchenowl  | /opt/venv/lib/python3.12/site-packages/pyRdfa/extras/httpheader.py:518: SyntaxWarning: invalid escape sequence '\-'
kitchenowl  |   """Parses a ()-style comment from a header value.
kitchenowl  | /opt/venv/lib/python3.12/site-packages/pyRdfa/termorcurie.py:61: SyntaxWarning: invalid escape sequence '\+'
kitchenowl  |   xml_application_media_type = re.compile("application/[a-zA-Z0-9]+\+xml")
kitchenowl  | /opt/venv/lib/python3.12/site-packages/pyRdfa/utils.py:131: SyntaxWarning: invalid escape sequence '\?'
kitchenowl  |   _unquotedChars = ':/\?=#~'
kitchenowl  | /usr/src/kitchenowl/migrations/env.py:21: DeprecationWarning: 'get_engine' is deprecated and will be removed in Flask-SQLAlchemy 3.2. Use 'engine' or 'engines[key]' instead. If you're using Flask-Migrate or Alembic, you'll need to update your 'env.py' file.
kitchenowl  |   return current_app.extensions['migrate'].db.get_engine()
kitchenowl  | /usr/src/kitchenowl/migrations/env.py:21: DeprecationWarning: 'get_engine' is deprecated and will be removed in Flask-SQLAlchemy 3.2. Use 'engine' or 'engines[key]' instead. If you're using Flask-Migrate or Alembic, you'll need to update your 'env.py' file.
kitchenowl  |   return current_app.extensions['migrate'].db.get_engine()
kitchenowl  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
kitchenowl  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Upgrading households: 0it [00:00, ?it/s]
kitchenowl  | [uWSGI] getting INI configuration from wsgi.ini
kitchenowl  | [uwsgi-static] added mapping for / => /var/www/web/kitchenowl
kitchenowl  | *** Starting uWSGI 2.0.25.1 (64bit) on [Mon Jul 15 09:43:14 2024] ***
kitchenowl  | compiled with version: 12.2.0 on 24 April 2024 13:24:45
kitchenowl  | os: Linux-6.9.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 21 Jun 2024 19:49:19 +0000
kitchenowl  | nodename: 0a9d94a92447
kitchenowl  | machine: x86_64
kitchenowl  | clock source: unix
kitchenowl  | pcre jit disabled
kitchenowl  | detected number of CPU cores: 12
kitchenowl  | current working directory: /usr/src/kitchenowl
kitchenowl  | detected binary path: /opt/venv/bin/uwsgi
kitchenowl  | *** dumping internal routing table ***
kitchenowl  | [rule: 0] subject: path_info regexp: ^\/(?!api)[^\.]*$ action: static:/var/www/web/kitchenowl/index.html
kitchenowl  | *** end of the internal routing table ***
kitchenowl  | uWSGI running as root, you can use --uid/--gid/--chroot options
kitchenowl  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
kitchenowl  | your memory page size is 4096 bytes
kitchenowl  | detected max file descriptor number: 1073741816
kitchenowl  | !!! no /etc/mime.types file found !!!
kitchenowl  | - async cores set to 200 - fd table size: 1073741816
kitchenowl  | lock engine: pthread robust mutexes
kitchenowl  | thunder lock: disabled (you can enable it with --thunder-lock)
kitchenowl  | uWSGI http bound on [::]:8080 fd 3
kitchenowl  | uwsgi socket 0 bound to TCP6 address [::]:5000 fd 6
kitchenowl  | uWSGI running as root, you can use --uid/--gid/--chroot options
kitchenowl  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
kitchenowl  | Python version: 3.12.3 (main, Apr 10 2024, 03:39:08) [GCC 12.2.0]
kitchenowl  | Python main interpreter initialized at 0x7cbe18cf4668
kitchenowl  | uWSGI running as root, you can use --uid/--gid/--chroot options
kitchenowl  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
kitchenowl  | python threads support enabled
kitchenowl  | your server socket listen backlog is limited to 100 connections
kitchenowl  | your mercy for graceful operations on workers is 60 seconds
kitchenowl  | mapped 4307328 bytes (4206 KB) for 200 cores
kitchenowl  | *** Operational MODE: async ***
kitchenowl  | uWSGI running as root, you can use --uid/--gid/--chroot options
kitchenowl  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
kitchenowl  | spawned uWSGI master process (pid: 59)
kitchenowl  | spawned uWSGI worker 1 (pid: 60, cores: 200)
kitchenowl  | spawned uWSGI http 1 (pid: 61)
kitchenowl  | respawned uWSGI http 1 (pid: 62)
kitchenowl  | respawned uWSGI http 1 (pid: 64)
kitchenowl  | respawned uWSGI http 1 (pid: 76)
kitchenowl  | respawned uWSGI http 1 (pid: 88)
kitchenowl  | respawned uWSGI http 1 (pid: 89)
kitchenowl  | respawned uWSGI http 1 (pid: 90)
kitchenowl  | WSGI app 0 (mountpoint='') ready in 7 seconds on interpreter 0x7cbe18cf4668 pid: 60 (default app)
kitchenowl  | *** running gevent loop engine [addr:0x5e5664853ba0] ***
kitchenowl  | respawned uWSGI http 1 (pid: 91)
kitchenowl  | respawned uWSGI http 1 (pid: 92)
kitchenowl  | respawned uWSGI http 1 (pid: 93)
kitchenowl  | respawned uWSGI http 1 (pid: 94)
kitchenowl  | respawned uWSGI http 1 (pid: 95)
kitchenowl  | respawned uWSGI http 1 (pid: 96)
kitchenowl  | respawned uWSGI http 1 (pid: 97)
kitchenowl  | respawned uWSGI http 1 (pid: 98)
kitchenowl  | respawned uWSGI http 1 (pid: 99)
kitchenowl  | respawned uWSGI http 1 (pid: 100)
kitchenowl  | respawned uWSGI http 1 (pid: 101)
kitchenowl  | respawned uWSGI http 1 (pid: 102)
kitchenowl  | respawned uWSGI http 1 (pid: 103)
kitchenowl  | respawned uWSGI http 1 (pid: 104)
kitchenowl  | respawned uWSGI http 1 (pid: 105)
kitchenowl  | respawned uWSGI http 1 (pid: 106)
```

My host is Arch (6.9.6-arch1-1 kernel).

Would be great if you could have another look at it.

**Comment by Tarow** [comment]
After some digging, i was able to solve it.
Turns out that the issue is related to the `fs.nr_open` sysctl property.

On my system it is set to `1073741816`, which seems to be a lot higher than the default on Ubuntu based systems for example.
Apparently this leads to uwsgi consuming more RAM: https://github.com/unbit/uwsgi/issues/2299

I worked around it by passing the `max-fd` option to uwsgi now:
```yaml
services:
  kitchenowl:
    image: tombursch/kitchenowl:latest
    container_name: kitchenowl
    restart: unless-stopped
    command: ["--ini", "wsgi.ini:web", "--gevent", "200", "--max-fd", "1048576"]
    env_file:
      - .env
    volumes:
      - ./data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.kitchenowl.rule=Host(`kitchenowl.somedomain.com`)
      - traefik.http.routers.kitchenowl.entrypoints=websecure
      - traefik.http.routers.kitchenowl.middlewares=public-chain@file
      - traefik.http.services.kitchenowl.loadbalancer.server.port=8080
    networks:
      - traefik-proxy
networks:
  traefik-proxy:
    external: true
```

Memory usage now sits at around 300MB as well. Maybe it helps someone.
