### ISSUE TITLE
Bug: Backend returns 502 errors

### ISSUE THREAD

**Issue by Ombrelin** [TomBursch/kitchenowl#201]
### Is this urgent?

Yes

### What parts are affected

Backend

### What are the Server/Client versions of KitchenOwl

0.4.6

### What's the problem 🤔

I'm running behind Traefik. The API only return 502 errors, even when calling form postman.

I had a look at #78 , but my traefik doesn't have `traefik.http.middlewares.security-headers.headers.sslredirect` nor `traefik.http.middlewares.security-headers.headers.contentsecuritypolicy` in its config.

### Share your logs

```log
/usr/src/kitchenowl/migrations/env.py:21: DeprecationWarning: 'get_engine' is deprecated and will be removed in Flask-SQLAlchemy 3.1. Use 'engine' or 'engines[key]' instead.
  return current_app.extensions['migrate'].db.get_engine()
/usr/src/kitchenowl/migrations/env.py:21: DeprecationWarning: 'get_engine' is deprecated and will be removed in Flask-SQLAlchemy 3.1. Use 'engine' or 'engines[key]' instead.
  return current_app.extensions['migrate'].db.get_engine()
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
[uWSGI] getting INI configuration from wsgi.ini
*** Starting uWSGI 2.0.21 (64bit) on [Fri Jul 21 18:38:03 2023] ***
compiled with version: 12.2.0 on 19 July 2023 16:12:48
os: Linux-5.15.0-75-generic #82-Ubuntu SMP Tue Jun 6 23:10:23 UTC 2023
nodename: 9dd53f74e5c8
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /usr/src/kitchenowl
detected binary path: /opt/venv/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:80 fd 3
uwsgi socket 0 bound to TCP address 0.0.0.0:5000 fd 6
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.11.4 (main, Jul  4 2023, 05:35:05) [GCC 12.2.0]
Python main interpreter initialized at 0x7fd9ddd76578
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 25)
spawned uWSGI worker 1 (pid: 26, cores: 1)
spawned uWSGI http 1 (pid: 27)
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x7fd9ddd76578 pid: 26 (default app)
[pid: 26|app: 0|req: 1/1] 127.0.0.1 () {28 vars in 373 bytes} [Fri Jul 21 18:38:59 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
[pid: 26|app: 0|req: 2/2] 127.0.0.1 () {28 vars in 373 bytes} [Fri Jul 21 18:39:59 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 26|app: 0|req: 3/3] 127.0.0.1 () {28 vars in 372 bytes} [Fri Jul 21 18:41:00 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
[pid: 26|app: 0|req: 4/4] 127.0.0.1 () {28 vars in 372 bytes} [Fri Jul 21 18:42:00 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
invalid request block size: 21573 (max 4096)...skip
[pid: 26|app: 0|req: 5/5] 127.0.0.1 () {28 vars in 373 bytes} [Fri Jul 21 18:43:00 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 26|app: 0|req: 6/6] 127.0.0.1 () {28 vars in 373 bytes} [Fri Jul 21 18:44:00 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 26|app: 0|req: 7/7] 127.0.0.1 () {28 vars in 372 bytes} [Fri Jul 21 18:45:00 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 26|app: 0|req: 8/8] 127.0.0.1 () {28 vars in 371 bytes} [Fri Jul 21 18:46:00 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 26|app: 0|req: 9/9] 127.0.0.1 () {28 vars in 373 bytes} [Fri Jul 21 18:47:00 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 26|app: 0|req: 10/10] 127.0.0.1 () {28 vars in 373 bytes} [Fri Jul 21 18:48:00 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 26|app: 0|req: 11/11] 127.0.0.1 () {28 vars in 373 bytes} [Fri Jul 21 18:49:01 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 26|app: 0|req: 12/12] 127.0.0.1 () {28 vars in 373 bytes} [Fri Jul 21 18:50:01 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 26|app: 0|req: 13/13] 127.0.0.1 () {28 vars in 373 bytes} [Fri Jul 21 18:51:01 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 26|app: 0|req: 14/14] 127.0.0.1 () {28 vars in 373 bytes} [Fri Jul 21 18:52:01 2023] GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V => generated 52 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
```

Each time I issue a call, a new `invalid request block size: 21573 (max 4096)...skip` line pops

### Share your configuration

```yml
kitchenowlfront:
    image: tombursch/kitchenowl-web:latest
    container_name: kitchenowlfront
    restart: unless-stopped
    depends_on:
      - kitchenowlback
    environment: 
      - BACK_URL=api.recipes.mydomain.com:443
    labels:
      - traefik.http.routers.kitchenowlfront.rule=Host(`recipes.mydomain.com.`)
      - traefik.http.routers.kitchenowlfront.tls=true
      - traefik.http.routers.kitchenowlfront.tls.certresolver=le

  kitchenowlback:
    image: tombursch/kitchenowl:latest
    container_name: kitchenowlback
    environment:
      - JWT_SECRET_KEY=secret
      - DB_DRIVER=postgresql
      - DB_HOST=db
      - DB_NAME=kitchenowl
      - DB_USER=secret
      - DB_PASSWORD=secret
    volumes: 
      - /home/me/kitchenowl:/data
    labels:
      - traefik.http.routers.kitchenowlback.rule=Host(`api.recipes.mydomain.com.`)
      - traefik.http.routers.kitchenowlback.tls=true
      - traefik.http.routers.kitchenowlback.tls.certresolver=le
      - traefik.http.services.kitchenowlback.loadbalancer.server.port=5000
```

**Comment by Ombrelin** [comment]
Okay I got it after fiddling and some thinking : I should not create two public apps, the frontend will proxy the API.  
So I went with this, works like a charm !

```
  kitchenowlfront:
    image: tombursch/kitchenowl-web:latest
    container_name: kitchenowlfront
    restart: unless-stopped
    depends_on:
      - kitchenowlback
    environment: 
      - BACK_URL=kitchenowlback:5000
    labels:
      - traefik.http.routers.kitchenowlfront.rule=Host(`recipes.mydomain.com.`)
      - traefik.http.routers.kitchenowlfront.tls=true
      - traefik.http.routers.kitchenowlfront.tls.certresolver=le

  kitchenowlback:
    image: tombursch/kitchenowl:latest
    container_name: kitchenowlback
    environment:
      - JWT_SECRET_KEY=secret
      - DB_DRIVER=postgresql
      - DB_HOST=db
      - DB_NAME=kitchenowl
      - DB_USER=secret
      - DB_PASSWORD=secret
    ports:
      - 5000:5000
    volumes: 
      - /home/arsene/kitchenowl:/data
      
      
```
