### ISSUE TITLE
Bug:  create multiple users

### ISSUE THREAD

**Issue by ALutz273** [TomBursch/kitchenowl#21]
### Is this urgent?

No

### What parts are affected

Both

### What are the Server/Client versions of KitchenOwl

v0.0.35 on docker

### What's the problem 🤔

It's now possible to create multiple user. 

### Share your logs

```log
[pid: 39|app: 0|req: 36/36] 172.21.0.1 () {48 vars in 1013 bytes} [Sat Apr 23 12:05:47 2022] POST /api/new-user => generated 28 bytes in 0 msecs (HTTP/1.1 404) 9 headers in 425 bytes (1 switches on core 0)
[pid: 39|app: 0|req: 37/37] 172.21.0.1 () {42 vars in 876 bytes} [Sat Apr 23 12:05:47 2022] GET /api/user/all => generated 197 bytes in 4 msecs (HTTP/1.1 200) 9 headers in 411 bytes (1 switches on core 0)
[pid: 39|app: 0|req: 38/38] 172.21.0.1 () {42 vars in 866 bytes} [Sat Apr 23 12:05:47 2022] GET /api/tag => generated 3 bytes in 3 msecs (HTTP/1.1 200) 9 headers in 409 bytes (1 switches on core 0)

Database: 
sqlite> select * from user;
1|andre|andre|xxxxxxxxxxxxxxxxxxxxxxxxxxxxx||1|2022-04-23 11:53:23.105973|2022-04-23 11:53:23.105977|0.0|0
```

### Share your configuration

```yml
ersion: "3"
services:
  front:
    image: tombursch/kitchenowl-web:latest
    environment:
      - FRONT_URL=http://laptop.fritz.box
      # - BACK_URL=back:5000 # Optional should not be changed unless you know what youre doing
    ports:
      - "80:80"
    depends_on:
      - back
    networks:
      - default
  back:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    # ports: # Optional and only needed when only hosting the backend
    #   - "80:80"
    networks:
      - default
    environment:
      - JWT_SECRET_KEY=PLEASE_CHANGE_ME
      # - FRONT_URL=http://localhost # Optional and only needed if 
      - FRONT_URL=http://laptop.fritz.box # Optional and only needed if 
    volumes:
    - ./data:/data

volumes:
  kitchenowl_data:

networks:
  default:
```
