### ISSUE TITLE
Bug(Android): Support user-installed certificates

### ISSUE THREAD

**Issue by Fen-nix** [TomBursch/kitchenowl#236]
### Is this urgent?

None

### What parts are affected

Both

### What are the Server/Client versions of KitchenOwl

Latest Client and Server (Docker)

### What's the problem 🤔

I've configured a reverse proxy for Apache and through a browser KitchenOwl is functioning just fine; However the Android app simply displays the message "Hmmmm... couldn't reach server".

The logs from the android device don't show any errors.

May relate to #211 but in my case the web works fine just the mobile app doesn't.

I have tested every permutation of hostname, IP, port, in the Android App's *Switch Server* screen. Examples:

- https://ko.lan.home
- https://ko.lan.home:5000
- https://10.x.x.x:5000
- https://10.x.x.x
- http://ko.lan.home:5000
- http://10.x.x.x:5000

Unless I'm missing it somewhere, the documentation doesn't really spell out how to connect the app to the selfhosted environment but the hint in the url entry when switching servers leads me to believe it needs to connect directly to the backend itself so I'd have expected at least one of the :5000 options above to work.

This is reverse proxied via Apache (though I've also tried it without this and the problem persists there too). TCP/8080 and TCP/5000 are both permitted via firewall.

Apache configuration:
```
<VirtualHost *:443>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        SSLEngine on
        SSLCertificateFile      /etc/pki/certs/ko.cer
        SSLCertificateKeyFile   /etc/pki/private/ko.key
        SSLCertificateChainFile /etc/pki/certs/chain.pem

        RewriteEngine On
        RewriteCond ${HTTP:Upgrade} websocket [NC]
        RewriteCond ${HTTP:Connection} upgrade [NC]
        RewriteRule .* "ws://localhost:8080/" [P,L]

        ProxyPreserveHost On
        ProxyPass / http://localhost:8080/
        ProxyPassReverse / http://localhost:8080/
</VirtualHost>
```

### Share your configuration

```yml
version: "3"
services:
  front:
    image: tombursch/kitchenowl-web:latest
    restart: unless-stopped
    environment:
      - FRONT_URL=https://ko.lan.home/
    ports:
      - "8080:80"
    depends_on:
      - back
  back:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    environment:
      - JWT_SECRET_KEY=<random data>
      - FRONT_URL=https://ko.lan.home/
    ports:
      - "5000:5000"
    volumes:
      - /home/ko/ko_data:/data
```
