### ISSUE TITLE
Bug: Constant connection loss

### ISSUE THREAD

**Issue by alphasierracharly** [TomBursch/kitchenowl#239]
### Is this urgent?

Yes

### What parts are affected

Backend

### What are the Server/Client versions of KitchenOwl

Latest

### What's the problem 🤔

Hi all,
I get constant disconnection from the server on a selfhostet instance and if it is working, it is generally very slow and almost irresponsive
Below is the seemingly relevant log entry found in the backend logs.
The frontens is entered via nginx as well. I tried both, mobile and web and both via nginx and directly via local IP. All with the same result as described above.

### Share your logs

```log
[2023-09-12 21:05:29,166] WARNING in config: Unauthorized: IP 172.21.0.1 reused the same refresh token, loging out user

[pid: 27|app: 0|req: 366/366] 172.21.0.1 () {54 vars in 1017 bytes} [Tue Sep 12 21:05:28 2023] GET /api/auth/refresh => generated 20 bytes in 1053 msecs (HTTP/1.1 401) 2 headers in 89 bytes (3 switches on core 198)
```

### Share your configuration

```yml
version: "3"
services:
    front:
        image: tombursch/kitchenowl-web:latest
        restart: unless-stopped
        container_name: kitchenowl-front
        ports:
        - "8030:80"
        depends_on:
        - back
    back:
        image: tombursch/kitchenowl:latest
        restart: unless-stopped
        container_name: kitchenowl-back
        environment:
        - JWT_SECRET_KEY=randomstring
        volumes:
        - /volume1/docker/kitchenowl:/data
```
