### ISSUE TITLE
Bug: Grayscreen when importing a recipe Android

### ISSUE THREAD

**Issue by helheimcloud** [TomBursch/kitchenowl#240]
### Is this urgent?

Yes

### What parts are affected

Frontend

### What are the Server/Client versions of KitchenOwl

0.4.11 / Server v76

### What's the problem 🤔

There is an app breaking bug when saving an imported recipe on the Android App. 

Phone: Xiaomi Mi11T Pro
Android 12

Running behind a reverse proxy - Sophos XGS

Unlisted: https://youtube.com/shorts/ML9Fl2DoIDs?si=6h4hmYZSIap0fAvv

I have realized this also happens on the web-based app after I recorded that snippet

### Share your configuration

```yml
version: "3"
services:
  front:
    image: tombursch/kitchenowl-web:latest
    restart: unless-stopped
    ports:
      - 8082:80
    depends_on:
      - back
  back:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    environment:
      - snip-jwt-key
    volumes:
      - kitchenowl_data:/data

volumes:
  kitchenowl_data:
```
