### ISSUE TITLE
Bug: Cannot rename item

### ISSUE THREAD

**Issue by adelolmo** [TomBursch/kitchenowl#241]
### Is this urgent?

No

### What parts are affected

Backend

### What are the Server/Client versions of KitchenOwl

Server: v76 Client: v0.4.11

### What's the problem 🤔

After creation of a new item, it's not possible to update the name.

### Share your logs

```log
neo-back-1   | [2023-09-14 15:14:45,007] ERROR in config: 'Blueprint' object has no attribute 'obj_to_dict'
neo-back-1   | [pid: 25|app: 0|req: 46/45] 172.20.0.1 () {70 vars in 1411 bytes} [Thu Sep 14 15:14:44 2023] POST /api/shoppinglist/1/item/459 => generated 20 bytes in 147 msecs (HTTP/1.0 500) 9 headers in 452 bytes (3 switches on core 199)
```

### Share your configuration

```yml
version: "3"
services:
  front:
    image: tombursch/kitchenowl-web:latest
    restart: unless-stopped
    environment:
      - BACK_URL=back:5000
      - FRONT_URL=https://domain.com
    ports:
      - "9999:80"
    depends_on:
      - back
  back:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    environment:
      - JWT_SECRET_KEY=xXxXxXx
      - FRONT_URL=https://domain.com
    volumes:
      - ./data:/data
```
