### ISSUE TITLE
Bug: invalid request block size: 21573 (max 4096)...skip

### ISSUE THREAD

**Issue by from-nibly** [TomBursch/kitchenowl#288]
### Is this urgent?

No

### What parts are affected

Backend

### What is the server version

v85

### What is the client version

v0.4.14

### What platform are you using

Linux

### What's the problem 🤔

When running in kubernetes I'm getting the following error when trying to start the new version

I've got kubernetes opening port 5000 but even having the wrong port open shouldn't make it so it can't start.

I noticed it was trying to listen on ivp6 for some reason. I don't have ipv6 enabled in my kubernetes cluster. Could that be it?

### Share your logs

```Shell
 ~/gh/from-nibly/cue-ops
on  master [$!?] ➜ ku logs -f kitchenowl-7747bdbf78-7cvzz
/usr/src/kitchenowl/migrations/env.py:21: DeprecationWarning: 'get_engine' is deprecated and will be removed in Flask-SQLAlchemy 3.2. Use 'engine' or 'engines[key]' instead. If you're using Flask-Migrate or Alembic, you'll need to updat
  return current_app.extensions['migrate'].db.get_engine()
/usr/src/kitchenowl/migrations/env.py:21: DeprecationWarning: 'get_engine' is deprecated and will be removed in Flask-SQLAlchemy 3.2. Use 'engine' or 'engines[key]' instead. If you're using Flask-Migrate or Alembic, you'll need to updat
  return current_app.extensions['migrate'].db.get_engine()
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Upgrading households...: 100%|██████████| 1/1 [00:01<00:00,  1.43s/it]
[uWSGI] getting INI configuration from wsgi.ini
*** Starting uWSGI 2.0.23 (64bit) on [Wed Nov 15 20:03:09 2023] ***
compiled with version: 12.2.0 on 13 November 2023 09:53:34
os: Linux-5.15.83 #1-NixOS SMP Wed Dec 14 10:37:31 UTC 2022
nodename: kitchenowl-7747bdbf78-7cvzz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 32
current working directory: /usr/src/kitchenowl
detected binary path: /opt/venv/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
- async cores set to 200 - fd table size: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP6 address [::]:5000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.11.6 (main, Nov  1 2023, 13:45:43) [GCC 12.2.0]
Python main interpreter initialized at 0x7f7b4c28deb8
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 4307328 bytes (4206 KB) for 200 cores
*** Operational MODE: async ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
spawned uWSGI master process (pid: 138)
spawned uWSGI worker 1 (pid: 139, cores: 200)
WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x7f7b4c28deb8 pid: 139 (default app)
*** running gevent loop engine [addr:0x5586a0c8e650] ***
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
```

### Share your configuration

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kitchenowl
    ops.davidson.house/generated-from: cue-ops
  name: kitchenowl
  namespace: family
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kitchenowl
  template:
    metadata:
      labels:
        app: kitchenowl
    spec:
      containers:
        - name: kitchenowl
          image: tombursch/kitchenowl:v85
          ports:
            - containerPort: 5000
              name: http
          envFrom:
            - secretRef:
                name: kitchenowl
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 5000
            failureThreshold: 30
            periodSeconds: 10
          env:
            - name: DB_DRIVER
              value: postgresql
            - name: DB_HOST
              value: postgres-postgresql-primary
            - name: DB_NAME
              value: kitchenowl
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: postgres-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: postgres-password
            - name: FRONT_URL
              value: kitchenowl.davidson.house
```
