### ISSUE TITLE
Bug(frontend): invalid host in upstream on changed service names

### ISSUE THREAD

**Issue by Rufmord** [TomBursch/kitchenowl#320]
### Is this urgent?

No

### What parts are affected

Both

### What is the server version

0.4.19 (current latest)

### What is the client version

newest on iOS

### What platform are you using

iOS, Web

### What's the problem 🤔

I edited the predefined docker compose file to fit my personal preference and needs. Thus I also edited the name of the backend service name and the environment variable `BACK_URL` for the frontend. But now I get errors in the frontend container and it keeps restarting. How to fix this? Thanks in advance.

### Share your logs

```Shell
Logs of frontend container
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/01-kitchenowl-customization.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/12/11 03:19:18 [emerg] 1#1: invalid host in upstream "http://kitchenowl-backend:5000" in /etc/nginx/conf.d/default.conf:16
nginx: [emerg] invalid host in upstream "http://kitchenowl-backend:5000" in /etc/nginx/conf.d/default.conf:16
```

### Share your configuration

```yml
services:
  postgres-kitchenowl:
    image: postgres:15
    container_name: postgres-kitchenowl
    restart: unless-stopped
    environment:
      POSTGRES_USER: kitchenowl
      POSTGRES_PASSWORD: # set via .env file
      POSTGRES_DB: kitchenowl
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 30s
    volumes:
      - $DOCKERDIR/apps/kitchenowl/database:/var/lib/postgresql/data
  kitchenowl-frontend:
    image: tombursch/kitchenowl-web:latest
    container_name: kitchenowl-frontend
    restart: unless-stopped
    environment:
      BACK_URL: http://kitchenowl-backend:5000
    depends_on:
      kitchenowl-backend:
        condition: service_healthy
  kitchenowl-backend:
    image: tombursch/kitchenowl:latest
    container_name: kitchenowl-backend
    restart: unless-stopped
    environment:
      FRONT_URL: https://kitchenowl.$DOMAIN
      JWT_SECRET_KEY: # set via .env file
      DB_DRIVER: postgresql
      DB_HOST: postgres-kitchenowl
      DB_NAME: kitchenowl
      DB_USER: kitchenowl
      DB_PASSWORD: $POSTGRES_PASSWORD
      SMTP_HOST: # set via .env file
      SMTP_PORT: # set via .env file
      SMTP_USER: # set via .env file
      SMTP_PASS: # set via .env file
      SMTP_FROM: # set via .env file
    depends_on:
      postgres-kitchenowl:
        condition: service_healthy
    volumes:
      - $DOCKERDIR/apps/kitchenowl/data:/data
```
