### ISSUE TITLE
Bug: On a machine that doesn't have IPv6, errors starting...

### ISSUE THREAD

**Issue by datdamnzotz** [TomBursch/kitchenowl#326]
### Is this urgent?

Yes

### What parts are affected

Backend

### What is the server version

0.4.20

### What is the client version

0.4.20

### What platform are you using

Web, Linux

### What's the problem 🤔

On a machine that doesn't have IPv6, errors starting...

### Share your logs

```Shell
docker-compose up
[+] Running 2/2
⠿ Container kitchenowl-back-1 Recreated 0.1s
⠿ Container kitchenowl-front-1 Recreated 0.0s
Attaching to kitchenowl-back-1, kitchenowl-front-1
kitchenowl-front-1 | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
kitchenowl-front-1 | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
kitchenowl-front-1 | /docker-entrypoint.sh: Launching /docker-entrypoint.d/01-kitchenowl-customization.sh
kitchenowl-front-1 | 01-kitchenowl-customization.sh: info: ipv6 not available
kitchenowl-front-1 | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
kitchenowl-front-1 | 10-listen-on-ipv6-by-default.sh: info: ipv6 not available
kitchenowl-front-1 | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
kitchenowl-front-1 | 20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
kitchenowl-front-1 | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
kitchenowl-front-1 | /docker-entrypoint.sh: Configuration complete; ready for start up
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: using the "epoll" event method
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: nginx/1.24.0
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4)
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: OS: Linux 5.15.0-86-generic
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: start worker processes
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: start worker process 28
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: start worker process 29
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: start worker process 30
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: start worker process 31
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: start worker process 32
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: start worker process 33
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: start worker process 34
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: start worker process 35
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: start worker process 36
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: start worker process 37
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: start worker process 38
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: start worker process 39
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: start worker process 40
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: start worker process 41
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: start worker process 42
kitchenowl-front-1 | 2023/12/21 22:56:43 [notice] 1#1: start worker process 43
kitchenowl-back-1 | /usr/src/kitchenowl/migrations/env.py:21: DeprecationWarning: 'get_engine' is deprecated and will be removed in Flask-SQLAlchemy 3.2. Use 'engine' or 'engines[key]' instead. If you're using Flask-Migrate or Alembic, you'll need to update your 'env.py' file.
kitchenowl-back-1 | return current_app.extensions['migrate'].db.get_engine()
kitchenowl-back-1 | /usr/src/kitchenowl/migrations/env.py:21: DeprecationWarning: 'get_engine' is deprecated and will be removed in Flask-SQLAlchemy 3.2. Use 'engine' or 'engines[key]' instead. If you're using Flask-Migrate or Alembic, you'll need to update your 'env.py' file.
kitchenowl-back-1 | return current_app.extensions['migrate'].db.get_engine()
kitchenowl-back-1 | INFO [alembic.runtime.migration] Context impl SQLiteImpl.
kitchenowl-back-1 | INFO [alembic.runtime.migration] Will assume non-transactional DDL.
Upgrading households: 0it [00:00, ?it/s]
kitchenowl-back-1 | [uWSGI] getting INI configuration from wsgi.ini
kitchenowl-back-1 | *** Starting uWSGI 2.0.23 (64bit) on [Thu Dec 21 22:56:51 2023] ***
kitchenowl-back-1 | compiled with version: 12.2.0 on 13 December 2023 14:57:18
kitchenowl-back-1 | os: Linux-5.15.0-86-generic https://github.com/davideshay/groceries/pull/96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023
kitchenowl-back-1 | nodename: c608fbffdb39
kitchenowl-back-1 | machine: x86_64
kitchenowl-back-1 | clock source: unix
kitchenowl-back-1 | pcre jit disabled
kitchenowl-back-1 | detected number of CPU cores: 16
kitchenowl-back-1 | current working directory: /usr/src/kitchenowl
kitchenowl-back-1 | detected binary path: /opt/venv/bin/uwsgi
kitchenowl-back-1 | uWSGI running as root, you can use --uid/--gid/--chroot options
kitchenowl-back-1 | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
kitchenowl-back-1 | your memory page size is 4096 bytes
kitchenowl-back-1 | detected max file descriptor number: 1048576
kitchenowl-back-1 | - async cores set to 200 - fd table size: 1048576
kitchenowl-back-1 | lock engine: pthread robust mutexes
kitchenowl-back-1 | thunder lock: disabled (you can enable it with --thunder-lock)
kitchenowl-back-1 | socket(): Address family not supported by protocol [core/socket.c line 82]
kitchenowl-back-1 exited with code 0
```

### Share your configuration

```yml
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 22.04.3 LTS
Release: 22.04
Codename: jammy

Docker version 24.0.7, build afdd53b
Docker Compose version v2.14.1
Ubuntu 22.04.

version: "3"
services:
  front:
    image: tombursch/kitchenowl-web:latest
    restart: unless-stopped
    # environment:
    #   - BACK_URL=back:5000 # Change this if you rename the containers
    #ports:
    #  - "9001:80"
    depends_on:
      - back
    networks:
      - proxy
      - kitchenowl
  back:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    # ports: # Should only be needed if you're not using docker-compose
    #   - "5000:5000" # uwsgi protocol
    environment:
      - JWT_SECRET_KEY=******
      # - FRONT_URL=http://localhost # Optional should not be changed unless you know what youre doing
    volumes:
      - ./data:/data
    networks:
      - kitchenowl

networks:
  kitchenowl:
  proxy:
    external: true
```
