### ISSUE TITLE
Bug: "onboarding" screen black on initial deployment

### ISSUE THREAD

**Issue by voyager529** [TomBursch/kitchenowl#396]
### Is this urgent?

No

### What parts are affected

Frontend

### What is the server version

v0.4.21

### What is the client version

n/a - browser issue

### What platform are you using

Web

### What's the problem 🤔

I'll preface this by stating that this is almost definitely user error rather than a bug...but there was no category for that =).

Initial install of the Docker Compose was performed, per the documentation, changing only the exposed port, the volume, and the secret key.

When I go to the LAN IP:88, I get a "/onboarding" page, which seems to get the CSS code when I do a view source, but it's otherwise blank.

### Share your logs

```Shell
Nothing stood out to me in the logs (i.e. there were no errors shown in the logs of either container), but I'd be happy to share any logs on request.
```

### Share your configuration

```yml
version: "3"
services:
  front:
    image: tombursch/kitchenowl-web:latest
    restart: unless-stopped
    ports:
      - "88:80"
    depends_on:
      - back
  back:
    image: tombursch/kitchenowl:latest
    restart: always
    environment:
      - JWT_SECRET_KEY=REDACTED
    volumes:
      - nfs.kitchenowl:/data

volumes:
  nfs.kitchenowl:
```
