### ISSUE TITLE
Bug: Logged out in browser after refreshing page

### ISSUE THREAD

**Issue by Timoses** [TomBursch/kitchenowl#400]
### Is this urgent?

No

### What parts are affected

Frontend

### What is the server version

0.4.21

### What is the client version

Browser

### What platform are you using

Mac

### What's the problem 🤔

Using Firefox:
1. Log into kitchenowl
2. Refresh (pressing Cmd+r)
3. Lands on `/signin` page.

### Share your logs

```Shell
172.18.0.1 - - [17/Feb/2024:19:29:55 +0000] "POST /api/auth HTTP/1.1" 200 686 "https://owl.robinia.dynu.net/signin" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:29:55 +0000] "GET /socket.io/?EIO=4&transport=polling&t=lsqh4ddi HTTP/1.1" 200 108 "https://owl.robinia.dynu.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:29:55 +0000] "GET /api/user HTTP/1.1" 200 550 "https://owl.robinia.dynu.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:29:55 +0000] "POST /socket.io/?EIO=4&transport=polling&t=lsqh4dff&sid=d5Z5bQzCMJJgKQShAAA- HTTP/1.1" 200 12 "https://owl.robinia.dynu.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:29:55 +0000] "GET /socket.io/?EIO=4&transport=polling&t=lsqh4dfg&sid=d5Z5bQzCMJJgKQShAAA- HTTP/1.1" 200 43 "https://owl.robinia.dynu.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:29:55 +0000] "GET /api/household/1/shoppinglist HTTP/1.1" 200 391 "https://owl.robinia.dynu.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:29:55 +0000] "GET /api/household/1/tag HTTP/1.1" 200 3 "https://owl.robinia.dynu.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:29:56 +0000] "GET /api/household/1/recipe HTTP/1.1" 200 5631 "https://owl.robinia.dynu.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:29:56 +0000] "GET /api/household/1/planner/suggested-recipes HTTP/1.1" 200 3 "https://owl.robinia.dynu.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:29:56 +0000] "GET /api/household/1/planner HTTP/1.1" 200 3 "https://owl.robinia.dynu.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:29:56 +0000] "GET /api/household/1 HTTP/1.1" 200 662 "https://owl.robinia.dynu.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:29:56 +0000] "GET /api/household/1/planner/recent-recipes HTTP/1.1" 200 3 "https://owl.robinia.dynu.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:29:56 +0000] "GET /api/household/1/expense/categories HTTP/1.1" 200 3 "https://owl.robinia.dynu.net/household/1/items" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:29:56 +0000] "GET /api/household/1/expense?view=0 HTTP/1.1" 200 3 "https://owl.robinia.dynu.net/household/1/items" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:29:56 +0000] "GET /api/shoppinglist/1/items?orderby=2 HTTP/1.1" 200 3 "https://owl.robinia.dynu.net/household/1/items" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:29:56 +0000] "GET /api/household/1/category HTTP/1.1" 200 1833 "https://owl.robinia.dynu.net/household/1/items" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:29:56 +0000] "GET /api/shoppinglist/1/recent-items?limit=9 HTTP/1.1" 200 3058 "https://owl.robinia.dynu.net/household/1/items" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:30:00 +0000] "GET /socket.io/?EIO=4&transport=polling&t=lsqh4djx&sid=d5Z5bQzCMJJgKQShAAA- HTTP/1.1" 499 0 "https://owl.robinia.dynu.net/household/1/items" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:30:00 +0000] "POST /socket.io/?EIO=4&transport=polling&t=lsqh4he3&sid=d5Z5bQzCMJJgKQShAAA- HTTP/1.1" 200 12 "https://owl.robinia.dynu.net/household/1/items" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:30:00 +0000] "GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V HTTP/1.1" 200 71 "https://owl.robinia.dynu.net/household/1/items" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:30:00 +0000] "GET /household/1/items HTTP/1.1" 200 3413 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:30:00 +0000] "GET /api/auth/refresh HTTP/1.1" 499 0 "https://owl.robinia.dynu.net/household/1/items" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:30:01 +0000] "GET /flutter_service_worker.js?v=3875269676 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:30:01 +0000] "GET /version.json?cachebuster=1708198235674 HTTP/1.1" 200 92 "https://owl.robinia.dynu.net/household/1/items" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:30:01 +0000] "GET /api/health/8M4F88S8ooi4sMbLBfkkV7ctWwgibW6V HTTP/1.1" 200 71 "https://owl.robinia.dynu.net/household/1/items" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:30:02 +0000] "GET /api/auth/refresh HTTP/1.1" 401 20 "https://owl.robinia.dynu.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
172.18.0.1 - - [17/Feb/2024:19:30:02 +0000] "GET /api/onboarding HTTP/1.1" 200 21 "https://owl.robinia.dynu.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "10.200.1.93"
```
```


### Share your configuration

```yml
Only configured this:

BACK_URL: kitchenowl_back:5000
```

Complete config with Ansible:
```
- name: Create docker network
  community.docker.docker_network:
    name: kitchenowl

- name: Create PSQL container
  community.docker.docker_container:
    name: kitchenowl_db
    image: postgres:15
    restart_policy: always
    env:
      POSTGRES_DB: kitchenowl
      POSTGRES_USER: "{{ kitchenowl_psql_user }}"
      POSTGRES_PASSWORD: "{{ kitchenowl_psql_password }}"
    networks:
      - name: kitchenowl
    volumes:
      - /var/www/html/kitchenowl/db:/var/lib/postgresql/data

- name: Create Backend container
  community.docker.docker_container:
    name: kitchenowl_back
    image: tombursch/kitchenowl:v92
    restart_policy: always
    env:
      JWT_SECRET_KEY: "{{ kitchenowl_jwt_secret_key }}"
      DB_DRIVER: postgresql
      DB_HOST: kitchenowl_db
      DB_NAME: kitchenowl
      DB_USER: "{{ kitchenowl_psql_user }}"
      DB_PASSWORD: "{{ kitchenowl_psql_password }}"
      FRONT_URL: https://owl.robinia.dynu.net
    networks:
      - name: kitchenowl
    volumes:
      - /var/www/html/kitchenowl/files:/data

- name: Create Frontend container
  community.docker.docker_container:
    name: kitchenowl_front
    image: tombursch/kitchenowl-web:v0.4.21
    restart_policy: always
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - name: kitchenowl
    env:
      BACK_URL: kitchenowl_back:5000
```
```
