### ISSUE TITLE
Bug: Docker compose (All-in-one) does not work correctly

### ISSUE THREAD

**Issue by adnanjaw** [TomBursch/kitchenowl#463]
### Is this urgent?

No

### What parts are affected

Frontend

### What is the server version

latest

### What is the client version

latest

### What platform are you using

Linux

### What's the problem 🤔

Im using [Docker compose (All-in-one) BETA](https://docs.kitchenowl.org/self-hosting/#__tabbed_1_3) to setup kitchenowl with traefik. When i go to the web application using the URL https://shopping.example.com i get the following:

![image](https://github.com/TomBursch/kitchenowl/assets/54184039/4afa197e-be4d-433a-ae12-61cfed9c2246)

 **NOTE:**
it works perfectly when connecting to the server from the IOS app.

### Share your configuration

```yml
services:
  kitchenowl:
    container_name: kitchenowl
    image: tombursch/kitchenowl:latest
    restart: always
    ports:
      - "8182:8080"
    environment:
      FRONT_URL: "https://shopping.example.com"
      JWT_SECRET_KEY: "secret"
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.kitchenowl.rule: Host(`shopping.example.com`)
      traefik.http.routers.kitchenowl.service: kitchenowl
      traefik.http.services.kitchenowl.loadbalancer.server.port: 8080
      traefik.http.routers.kitchenowl.entrypoints: https
      traefik.http.routers.kitchenowl.tls: true
      traefik.http.routers.kitchenowl.tls.certresolver: prod
      traefik.http.routers.kitchenowl.middlewares: security@docker
      traefik.http.middlewares.security.headers.addvaryheader: true
      traefik.http.middlewares.security.headers.sslredirect: true
      traefik.http.middlewares.security.headers.browserxssfilter: true
      traefik.http.middlewares.security.headers.contenttypenosniff: true
      traefik.http.middlewares.security.headers.forcestsheader: true
      traefik.http.middlewares.security.headers.stsincludesubdomains: true
      traefik.http.middlewares.security.headers.stspreload: true
      traefik.http.middlewares.security.headers.stsseconds: 63072000
      traefik.http.middlewares.security.headers.customframeoptionsvalue: SAMEORIGIN
      traefik.http.middlewares.security.headers.referrerpolicy: same-origin
    networks:
      - proxy
    volumes:
      - kitchenowl_data:/data

volumes:
  kitchenowl_data:
networks:
  proxy:
```
