### ISSUE TITLE
Bug: kitchenowl-web fails to start without root privileges

### ISSUE THREAD

**Issue by fynnos** [TomBursch/kitchenowl#50]
### Is this urgent?

No

### What parts are affected

Backend

### What are the Server/Client versions of KitchenOwl

v0.3.2

### What's the problem 🤔

kitchenowl-web requires root privileges to run and fails to start without (by specifying non-root user in docker-compose.yml)

### Share your logs

```log
kitchenowl-front-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/entrypoint.sh
kitchenowl-front-1  | /docker-entrypoint.d/entrypoint.sh: line 4: can't create /var/www/web/kitchenowl/assets/.env: Permission denied
kitchenowl-front-1  | /docker-entrypoint.d/entrypoint.sh: line 5: can't create /var/www/web/kitchenowl/assets/.env: Permission denied
```

### Share your configuration

```yml
version: "3"
services:
  front:
    image: tombursch/kitchenowl-web:latest
    environment:
      - FRONT_URL=<>
      - HTTP_PORT=2003
      - BACK_URL=back:2002 # Optional should not be changed unless you know what youre doing
    ports:
      - "127.0.0.1:2003:2003"
    depends_on:
      - back
    networks:
      - default
    user: 123:123
  back:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    ports: # Optional and only needed when only hosting the http backend
      - "127.0.0.1:2002:2002"
    environment:
      - JWT_SECRET_KEY=<>
      - FRONT_URL=<>
      - HTTP_PORT=2002
    volumes:
    - /opt/kitchenowl:/data
    networks:
      - default
    user: 123:123

networks:
  default:
```
