### ISSUE TITLE
Bug: Missing Mail Header 

### ISSUE THREAD

**Issue by OfficeRat** [TomBursch/kitchenowl#523]
### Is this urgent?

No

### What parts are affected

Backend

### What is the server version

v0.5.2

### What is the client version

v0.5.2

### What platform are you using

Android, iOS, Windows

### What's the problem 🤔

Only tried password reset as part of my testing of setting up email sending

When sending an email via docker mail-server i get this error

INVALID HEADER

  Missing required header field: "Date"
  
after looking through the code for the mail service i did notice that it wasn't adding date to the mail header.

heres the mail header (x is added by me)

Return-Path: [<xxxxxx@xxxxxx.xxx>](mailto:xxxxxx@xxxxxx.xxx)
DKIM-Signature: xxxxx
Content-Type: multipart/alternative; boundary="===============0608390932539680132=="
MIME-Version: 1.0
Subject: Reset password
From: [noreply@xxxxxx.xxx](mailto:noreply@xxxxxx.xxx)
To: [xxxx@xxxxxx.xxx](mailto:xxxx@xxxxxx.xxx)

maybe i have miss configured something but i do believe the date header should be present

### Share your logs

```Shell
No relevant docker logs
```

### Share your configuration

```yml
services:
  kitchenowl:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    ports:
      - 38429:80
    environment:
      - JWT_SECRET_KEY=$TOKEN
      - FRONT_URL=https://xx.xxxxxx.xxx/
      - SMTP_HOST=xx.xxxxxx.xxx
      - SMTP_PORT=465
      - SMTP_USER=xxxxxx@xxxxxx.xxx
      - SMTP_PASS=xxxxxxxx
      - SMTP_FROM=xxxxxx@xxxxxx.xxx
    volumes:
      - /mnt/docker/kitchenowl:/data
```
