### ISSUE TITLE
Bug: Share link adding a second Slash

### ISSUE THREAD

**Issue by miovo** [TomBursch/kitchenowl#603]
### Is this urgent?

No

### What parts are affected

Frontend

### What is the server version

v105

### What is the client version

v0.6.7

### What platform are you using

Web

### What's the problem 🤔

When sharing a recipe marked as "Public":
In the URL, After the domain. Instead of 1 slash, it adds 2 causing the page to not load. I have checked my proxy to see if there would be anything in there causing this issue and there is not. All of the other pages load just fine.

![image](https://github.com/user-attachments/assets/7e1eb1e5-9bef-42d8-8e53-34ffea2d65fd)

![image](https://github.com/user-attachments/assets/88e67208-a761-4624-830c-4ae4dc8cd477)

### Share your configuration

```yml
version: "3"
services:
  front:
    image: tombursch/kitchenowl-web:latest
    restart: unless-stopped
    # environment:
    #   - BACK_URL=back:5000 # Change this if you rename the containers
    ports:
      - "8090:80"
    depends_on:
      - back
  back:
    image: tombursch/kitchenowl-backend:latest
    restart: unless-stopped
    environment:
      - JWT_SECRET_KEY=********
    volumes:
      - /home/*****/kitchenowl_data:/data
```
