### ISSUE TITLE
Bug: Unauthorized IP

### ISSUE THREAD

**Issue by kmccmk9** [TomBursch/kitchenowl#625]
### Is this urgent?

Yes

### What parts are affected

Backend

### What is the server version

0.6.8

### What is the client version

0.6.8

### What platform are you using

Android, Web

### What's the problem 🤔

When attempting to log in with valid credentials, the frontend reports a wrong username/password. When checking the logs of the backend docker container, it specifies the following:

`[2025-01-08 19:04:14,031] WARNING in config: Unauthorized: IP 172.21.0.1 login attemp with wrong username or password`

The message seems clear that the IP of the docker frontend is not permitted, but I do not see any advanced configuration options to add it to the deployment. This error and resulting log appear no matter the browser, platform, and even when using the Flutter android app. I've also tried all of these tests using the unified docker container and experience the exact same problem. 

### Share your logs

```Shell
[2025-01-08 19:04:14,031] WARNING in config: Unauthorized: IP 172.21.0.1 login attemp with wrong username or password
```

### Share your configuration

```yml
version: "3"
services:
    front:
        image: tombursch/kitchenowl-web:v0.6.8
        restart: unless-stopped
        ports:
        - "5001:80"
        depends_on:
        - back
    back:
        image: tombursch/kitchenowl-backend:v0.6.8
        restart: unless-stopped

        environment:
        - JWT_SECRET_KEY=PLEASE_CHANGE_ME
        - FRONT_URL=https://url_here
        volumes:
        - kitchenowl_data:/data
        networks:
        - default
volumes:
    kitchenowl_data:

networks:
    default:
```
