### ISSUE TITLE
Bug: White bars in Expense Statistics

### ISSUE THREAD

**Issue by LeonSpahr** [TomBursch/kitchenowl#663]
### Is this urgent?

No

### What parts are affected

Frontend

### What is the server version

Server v106

### What is the client version

v0.6.8 (106)

### What platform are you using

Android, Web, iOS, Windows

### What's the problem 🤔

![Image](https://github.com/user-attachments/assets/f0165985-d43a-4035-92fc-e2fda7d6cf5e)
Hi, 
I created a household and started adding expenses.
Shortly after entering the newest expenses, the white bars appeared, as in the screenshot above.
I have tried exporting the data and creating a new household, but they appear every time.
Please find the config attached. To reproduce the bug on your side, add at least 2 expenses to your user and reload.
I have tried to reduce the amount of expenses in the import to narrow it down to one Item, but till now it hasn't worked.
I'm looking forward to your response.
With best regards,
Leon

[export.json](https://github.com/user-attachments/files/18923367/export.json)

### Share your logs

```Shell

```

### Share your configuration

```yml
version: "3"
services:
  front:
    image: tombursch/kitchenowl-web:latest
    restart: unless-stopped
    # environment:
    #   - BACK_URL=back:5000 # Change this if you rename the containers
    ports:
      - "8643:80"
    depends_on:
      - back
  back:
    image: tombursch/kitchenowl-backend:latest
    restart: unless-stopped
    environment:
      - JWT_SECRET_KEY=
    volumes:
      - kitchenowl_data:/data

volumes:
  kitchenowl_data:
```
