### ISSUE TITLE
Bug: No way to add/remove shopping lists

### ISSUE THREAD

**Issue by tlaerm** [TomBursch/kitchenowl#692]
### Is this urgent?

No

### What parts are affected

Frontend

### What is the server version

Server v109

### What is the client version

v0.6.11 (109)

### What platform are you using

Android

### What's the problem 🤔

I see no way to edit the shopping lists. We have multiple that we created a long time ago but now I wanted to add another one and cannot find a way. 
How is this supposed to work? There is nothing in the household settings, nothing on the shopping list page. 
I looked a the sqlite db and was able to manipulate them there. 

Any pointers would be greatly appreciated. 

### Share your logs

```Shell

```

### Share your configuration

```yml
version: "3"
services:
  front:
    image: tombursch/kitchenowl-web:latest
    restart: unless-stopped
    depends_on:
      - back
    labels:
      - "traefik.http.routers.kitchenowl.rule=(Host(`ko.domain.tld`))"
      - "traefik.http.routers.kitchenowl.tls.certresolver=letse"
      - "traefik.enable=true"
    networks:
      - internal
      - proxy
  back:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    volumes:
      - /docker-storage/kitchenowl:/data
    environment:
      - JWT_SECRET_KEY=***
      - FRONT_URL=https://ko.domain.tld
      - OIDC_ISSUER=https://oidc.domain.tld/oauth2/openid/kitchenowl
      - OIDC_CLIENT_ID=kitchenowl
      - OIDC_CLIENT_SECRET=***
    networks:
      - internal
networks:
  proxy:
    external: true
  internal:
    external: false
```
