### ISSUE TITLE
ERROR: no matching manifest for linux/arm/v7 in the manifest list entriesBug: 

### ISSUE THREAD

**Issue by Coolie1101** [TomBursch/kitchenowl#70]
### What parts are affected

Backend

### What are the Server/Client versions of KitchenOwl

Latest

### What's the problem 🤔

Got the following error while trying to install via docker-compose.

`ERROR: no matching manifest for linux/arm/v7 in the manifest list entries`

### Share your logs

```log
WARNING: The ZbF variable is not set. Defaulting to a blank string.
Pulling back (tombursch/kitchenowl:latest)...
latest: Pulling from tombursch/kitchenowl
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```

### Share your configuration

```yml
version: "3"
services:
  front:
    image: tombursch/kitchenowl-web:latest
    environment:
      - FRONT_URL=http://localhost
      # - BACK_URL=back:5000 # Optional should not be changed unless you know what youre doing
    ports:
      - "80:80"
    depends_on:
      - back
    networks:
      - default
  back:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    # ports: # Optional and only needed when only hosting the http backend
    #   - "80:80"
    networks:
      - default
    environment:
      - JWT_SECRET_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - FRONT_URL=http://localhost
    volumes:
    - kitchenowl_data:/data

volumes:
  kitchenowl_data:

networks:
  default:
```
