### ISSUE TITLE
Bug: Server can not be reached when using Desktop app

### ISSUE THREAD

**Issue by Kampi** [TomBursch/kitchenowl#786]
### Is this urgent?

No

### What parts are affected

Frontend

### What is the server version

v113

### What is the client version

Unknown

### What platform are you using

Windows

### What's the problem 🤔

I have KitchenOwl installed on my NAS and I can reach the web server by using the address http://192.168.178.103:8173. Adding this address and using my login from web in the desktop app results in this error:

![Image](https://github.com/user-attachments/assets/0c1e5aa7-d76f-4c8c-9d03-6eb1a02d1512)

### Share your logs

```Shell

```

### Share your configuration

```yml
version: "3"
services:
  KitchenOwl_Postgres:
    image: postgres:15
    container_name: KitchenOwl-Postgres
    restart: always
    environment:
      POSTGRES_DB: ...
      POSTGRES_USER: ...
      POSTGRES_PASSWORD: ...
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  KitchenOwl_Web:
    image: tombursch/kitchenowl:latest
    container_name: KitchenOwl-Web
    restart: always
    ports:
      - "8173:8080"
    environment:
      JWT_SECRET_KEY: ...
      DB_DRIVER: postgresql
      DB_HOST: KitchenOwl_Postgres
      DB_NAME: ...
      DB_USER: ...
      DB_PASSWORD: ...
    depends_on:
      - KitchenOwl_Postgres
    volumes:
      - ./data:/data
```
