### ISSUE TITLE
Bug: 404 on OIDC callback `/signin/redirect`

### ISSUE THREAD

**Issue by Ombrelin** [TomBursch/kitchenowl#796]
### Is this urgent?

No

### What parts are affected

Frontend

### What is the server version

latest (0.6.15)

### What is the client version

latest (0.6.15)

### What platform are you using

Web

### What's the problem 🤔

My OIDC setup with Keycloak has been working great for a long time now, but today after upgrade to the latest version, on the web version I don't get the "Log in with OIDC" button on the login page : 

![Image](https://github.com/user-attachments/assets/3999c81f-0904-46eb-bba4-c2371cd2fe84)

The login flow still works on the mobile app though

### Share your logs

```Shell

```

### Share your configuration

```yml
kitchenowlfront:
    image: tombursch/kitchenowl-web
    container_name: kitchenowlfront
    restart: unless-stopped
    depends_on:
      - kitchenowlback
    environment: 
      - BACK_URL=kitchenowlback:5000
    labels:
      - traefik.http.routers.kitchenowlfront.rule=Host(`recipes.************.fr.`)
      - traefik.http.routers.kitchenowlfront.tls=true
      - traefik.http.routers.kitchenowlfront.tls.certresolver=le

  kitchenowlback:
    image: tombursch/kitchenowl-backend
    container_name: kitchenowlback
    restart: unless-stopped
    environment:
      - JWT_SECRET_KEY=***
      - DB_DRIVER=postgresql
      - DB_HOST=***
      - DB_NAME=***
      - DB_USER=***
      - DB_PASSWORD=***
      - FRONT_URL=https://recipes.************.fr
      - OIDC_ISSUER=https://***********/realms/vostok
      - OIDC_CLIENT_ID=kitchen-owl
      - OIDC_CLIENT_SECRET=****
    ports:
      - 5000:5000
    volumes: 
      - /home/arsene/kitchenowl:/data
```
