### ISSUE TITLE
Bug: syntaxwarning in logs

### ISSUE THREAD

**Issue by roughnecks** [TomBursch/kitchenowl#809]
### Is this urgent?

No

### What parts are affected

Backend

### What is the server version

0.7.1

### What is the client version

0.7.1

### What's the problem 🤔

Hello,

I'm seeing a few lines with a "syntaxwarning" in logs, no idea what it is about.
I also have a bug with the balance sheets, but will post separately, if you tell this isn't related (just so you know, the statistics graph broke a few days ago.. it's not counting most of my expenses in a particular category and other minor annoyances which have always been there).

### Share your logs

```Shell
docker logs kitchen-back-1
/opt/venv/lib/python3.12/site-packages/pyRdfa/extras/httpheader.py:347: SyntaxWarning: invalid escape sequence '\-'
  have been removed and all \-escapes will have been replaced with
/opt/venv/lib/python3.12/site-packages/pyRdfa/extras/httpheader.py:359: SyntaxWarning: invalid escape sequence '\-'
  (token, chars_consumed), with all \-escapes and quotation already
/opt/venv/lib/python3.12/site-packages/pyRdfa/extras/httpheader.py:525: SyntaxWarning: invalid escape sequence '\-'
  All \-escaped quoted pairs will have been replaced with the actual
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 1d3c1e2061f6 -> caa4cab82b41, empty message
INFO  [alembic.runtime.migration] Running upgrade caa4cab82b41 -> aa5d56fe28bb, empty message
INFO  [alembic.runtime.migration] Running upgrade aa5d56fe28bb -> bd383e73ef4d, empty message
Upgrading households: 100%|██████████| 1/1 [00:02<00:00,  2.64s/it]
[uWSGI] getting INI configuration from wsgi.ini
*** Starting uWSGI 2.0.30 (64bit) on [Sun Jun 29 18:18:48 2025] ***
compiled with version: 12.2.0 on 29 June 2025 17:56:35
os: Linux-6.1.0-37-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.140-1 (2025-05-22)
nodename: c7864c4a826d
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /usr/src/kitchenowl
detected binary path: /opt/venv/bin/uwsgi
```

### Share your configuration

```yml
services:
  front:
    image: tombursch/kitchenowl-web:latest
    restart: unless-stopped
    ports:
      - "172.16.100.1:5001:80"
    depends_on:
      - back
  back:
    image: tombursch/kitchenowl-backend:latest
    restart: unless-stopped
    environment:
      - JWT_SECRET_KEY=secret
      - FRONT_URL=http://localhost:5001
    volumes:
      - ./data:/data
```
